import { useMemo, useState } from 'react'
import { BrowserRouter, Navigate, Route, Routes, useNavigate } from 'react-router-dom'
import {
  ArrowLeft,
  ArrowRight,
  Bell,
  BookOpen,
  CalendarDays,
  Check,
  ChevronDown,
  CircleUserRound,
  Filter,
  Heart,
  Home,
  Leaf,
  ListFilter,
  MapPin,
  Menu,
  Package,
  Pencil,
  Plus,
  Search,
  Settings,
  ShoppingBasket,
  Store,
  Tag,
  Ticket,
  UserPlus,
  Users,
  X,
} from 'lucide-react'

type View = 'home' | 'feiras' | 'produtos' | 'feira' | 'login' | 'cadastro' | 'feirante' | 'catalogo' | 'organizador' | 'minhas-feiras' | 'nova-feira' | 'manual'

const markets = [
  { id: 1, name: 'Feira do Jardim', place: 'Praça do Jardim Iririú', date: 'Sábado, 21 de setembro', time: '07:00 – 12:00', distance: '1,2 km', color: 'mint', emoji: '🥬', vendors: 24 },
  { id: 2, name: 'Feira da Vila Nova', place: 'Rua XV de Novembro, 420', date: 'Domingo, 22 de setembro', time: '08:00 – 13:00', distance: '3,8 km', color: 'peach', emoji: '🍊', vendors: 18 },
  { id: 3, name: 'Mercado da Estação', place: 'Estação da Memória', date: 'Quarta, 25 de setembro', time: '16:00 – 21:00', distance: '5,4 km', color: 'lavender', emoji: '🍞', vendors: 31 },
]

const products = [
  { name: 'Tomate italiano', vendor: 'Sítio Boa Terra', price: 'R$ 8,90/kg', category: 'Hortaliças', color: 'tomato', emoji: '🍅' },
  { name: 'Pão de fermentação natural', vendor: 'Pão da Ana', price: 'R$ 18,00', category: 'Panificação', color: 'bread', emoji: '🍞' },
  { name: 'Geleia de morango', vendor: 'Doces da Serra', price: 'R$ 16,50', category: 'Artesanais', color: 'jam', emoji: '🍓' },
  { name: 'Queijo colonial', vendor: 'Laticínios Estância', price: 'R$ 32,00/kg', category: 'Laticínios', color: 'cheese', emoji: '🧀' },
]

function Logo() { const navigate = useNavigate(); return <button className="logo" onClick={() => navigate('/')}><span className="logo-mark"><Leaf size={18} /></span> achei na <b>feira</b></button> }
function Button({ children, variant = 'primary', onClick, type = 'button' }: { children: React.ReactNode; variant?: 'primary' | 'outline' | 'soft' | 'ghost'; onClick?: () => void; type?: 'button' | 'submit' }) { return <button type={type} onClick={onClick} className={`button button-${variant}`}>{children}</button> }
function Header({ setView }: { setView: (view: View) => void }) {
  const [open, setOpen] = useState(false)
  return <header className="header"><div className="header-inner"><Logo /><nav className={open ? 'nav nav-open' : 'nav'}><button onClick={() => { setView('feiras'); setOpen(false) }}>Feiras</button><button onClick={() => { setView('produtos'); setOpen(false) }}>Produtos</button><button onClick={() => { setView('manual'); setOpen(false) }}><BookOpen size={15} /> Manual</button><button onClick={() => { setView('login'); setOpen(false) }} className="nav-login">Entrar</button><Button variant="primary" onClick={() => { setView('cadastro'); setOpen(false) }}>Criar conta <ArrowRight size={16} /></Button></nav><button className="mobile-menu" aria-label="Abrir menu" onClick={() => setOpen(!open)}>{open ? <X /> : <Menu />}</button></div></header>
}
function SearchBar({ onSearch }: { onSearch?: (value: string) => void }) { const [value, setValue] = useState(''); return <div className="searchbar"><Search size={19} /><input placeholder="O que você procura?" value={value} onChange={e => { setValue(e.target.value); onSearch?.(e.target.value) }} /><button aria-label="Buscar"><ArrowRight size={18} /></button></div> }
function MarketCard({ market, onClick }: { market: typeof markets[number]; onClick: () => void }) { return <button className="market-card" onClick={onClick}><div className={`market-image ${market.color}`}><span>{market.emoji}</span><small><MapPin size={12} /> {market.distance}</small></div><div className="market-content"><div className="eyebrow">PRÓXIMA FEIRA</div><h3>{market.name}</h3><p><MapPin size={14} /> {market.place}</p><p><CalendarDays size={14} /> {market.date} · {market.time}</p><div className="card-footer"><span>{market.vendors} feirantes</span><ArrowRight size={17} /></div></div></button> }
function ProductCard({ product }: { product: typeof products[number] }) { return <article className="product-card"><div className={`product-image ${product.color}`}><span>{product.emoji}</span><button aria-label="Favoritar"><Heart size={17} /></button></div><div className="product-content"><span className="tag">{product.category}</span><h3>{product.name}</h3><p>{product.vendor}</p><strong>{product.price}</strong></div></article> }
function Shell({ children, setView, active }: { children: React.ReactNode; setView: (v: View) => void; active?: View }) { return <><Header setView={setView} /><main>{children}</main><footer><Logo /><span>Comida boa, perto de você.</span><div><button onClick={() => setView('feiras')}>Encontrar feiras</button><button onClick={() => setView('cadastro')}>Quero vender</button></div></footer></> }
function HomePage({ setView }: { setView: (v: View) => void }) { return <Shell setView={setView}><section className="hero"><div className="hero-copy"><span className="kicker">COMIDA LOCAL, VIDA REAL</span><h1>Encontre o que é <em>feito perto.</em></h1><p>Feiras, produtores e sabores da sua cidade em um só lugar. Descubra, escolha e apoie quem faz acontecer.</p><SearchBar onSearch={() => setView('produtos')} /><div className="hero-links"><button onClick={() => setView('feiras')}>Ver feiras perto de mim <ArrowRight size={15} /></button><button onClick={() => setView('produtos')}>Explorar produtos <ArrowRight size={15} /></button></div></div><div className="hero-art"><div className="sun"></div><div className="art-card art-card-one">🥕<small>da terra<br /><b>pra sua mesa</b></small></div><div className="art-card art-card-two">🍓<small>feito com<br /><b>carinho</b></small></div><div className="art-note"><span>01</span><b>Descubra<br />o local</b></div></div></section><section className="section section-tint"><div className="section-heading"><div><span className="kicker">ACONTECE POR AQUI</span><h2>Feiras próximas</h2></div><button className="text-link" onClick={() => setView('feiras')}>Ver todas <ArrowRight size={16} /></button></div><div className="market-grid">{markets.slice(0, 3).map(m => <MarketCard key={m.id} market={m} onClick={() => setView('feira')} />)}</div></section><section className="section"><div className="section-heading"><div><span className="kicker">DO SEU BAIRRO</span><h2>Achados da semana</h2></div><button className="text-link" onClick={() => setView('produtos')}>Explorar produtos <ArrowRight size={16} /></button></div><div className="product-grid">{products.map(p => <ProductCard key={p.name} product={p} />)}</div></section><section className="join-banner"><div><span className="kicker">VOCÊ PRODUZ?</span><h2>Seu trabalho merece<br /><em>ser encontrado.</em></h2><p>Cadastre seus produtos e apareça para quem valoriza o que é local.</p><Button onClick={() => setView('cadastro')}>Quero ser feirante <ArrowRight size={16} /></Button></div><div className="join-art">🌱<span>feito<br />aqui</span></div></section></Shell> }
function Listing({ setView, productsOnly = false }: { setView: (v: View) => void; productsOnly?: boolean }) { const [query, setQuery] = useState(''); const filtered = products.filter(p => p.name.toLowerCase().includes(query.toLowerCase()) || p.vendor.toLowerCase().includes(query.toLowerCase())); return <Shell setView={setView}><section className="page-head"><div><span className="kicker">{productsOnly ? 'CATÁLOGO LOCAL' : 'DESCUBRA NA SUA CIDADE'}</span><h1>{productsOnly ? 'Produtos perto de você' : 'Feiras próximas'}</h1><p>{productsOnly ? 'Sabores, histórias e produtos feitos por quem está perto.' : 'Escolha uma feira, conheça os produtores e leve o melhor para casa.'}</p></div><SearchBar onSearch={setQuery} /></section><div className="filter-row"><Button variant="soft"><MapPin size={16} /> Joinville <ChevronDown size={15} /></Button><Button variant="outline"><CalendarDays size={16} /> Quando? <ChevronDown size={15} /></Button><Button variant="outline"><ListFilter size={16} /> Filtros</Button></div>{productsOnly ? <div className="product-grid listing-grid">{filtered.map(p => <ProductCard key={p.name} product={p} />)}</div> : <div className="market-grid listing-grid">{markets.map(m => <MarketCard key={m.id} market={m} onClick={() => setView('feira')} />)}</div>}</Shell> }
function FairDetail({ setView }: { setView: (v: View) => void }) { return <Shell setView={setView}><div className="detail-wrap"><button className="back-link" onClick={() => setView('feiras')}><ArrowLeft size={16} /> Voltar para feiras</button><div className="detail-hero"><div className="detail-visual mint">🥬<span>tudo fresco<br /><b>por aqui</b></span></div><div className="detail-info"><span className="kicker">SÁBADO, 21 DE SETEMBRO</span><h1>Feira do Jardim</h1><p className="lead"><MapPin size={17} /> Praça do Jardim Iririú · 07:00 – 12:00</p><p>Uma manhã para encontrar produtores locais, comer bem e conhecer histórias do nosso bairro.</p><div className="detail-actions"><Button><Ticket size={17} /> Quero visitar</Button><Button variant="outline"><Heart size={17} /> Salvar</Button></div></div></div><div className="detail-section"><div className="section-heading"><div><span className="kicker">24 FEIRANTES</span><h2>O que você encontra</h2></div><Button variant="soft" onClick={() => setView('produtos')}><Filter size={16} /> Filtrar</Button></div><div className="product-grid">{products.map(p => <ProductCard key={p.name} product={p} />)}</div></div></div></Shell> }
function Auth({ setView, signup = false }: { setView: (v: View) => void; signup?: boolean }) { return <main className="auth-page"><div className="auth-aside"><Logo /><div><span className="kicker">COMIDA LOCAL, VIDA REAL</span><h1>O melhor da cidade<br /><em>começa perto.</em></h1><p>Faça parte de uma comunidade que valoriza quem produz e quem escolhe consumir local.</p></div><span className="auth-caption">Joinville, SC · 2024</span></div><div className="auth-form-wrap"><button className="back-link" onClick={() => setView('home')}><ArrowLeft size={16} /> Voltar para o início</button><div className="auth-form"><span className="kicker">{signup ? 'BEM-VINDO À COMUNIDADE' : 'QUE BOM TER VOCÊ AQUI'}</span><h1>{signup ? 'Crie sua conta.' : 'Entre na sua conta.'}</h1><p>{signup ? 'Comece a descobrir e apoiar o que é local.' : 'Continue de onde parou.'}</p><form onSubmit={e => { e.preventDefault(); setView('feirante') }}><label>Seu e-mail<input type="email" placeholder="voce@email.com" required /></label>{signup && <label>Como você quer usar o Achei na Feira?<select><option>Quero encontrar feiras e produtos</option><option>Quero vender meus produtos</option><option>Quero organizar feiras</option></select></label>}<label>Senha<input type="password" placeholder="••••••••" required /></label><Button type="submit">{signup ? 'Criar minha conta' : 'Entrar'} <ArrowRight size={16} /></Button></form><div className="auth-switch">{signup ? 'Já tem uma conta?' : 'Ainda não tem uma conta?'} <button onClick={() => setView(signup ? 'login' : 'cadastro')}>{signup ? 'Entrar' : 'Criar conta'}</button></div></div></div></main> }
function DashboardNav({ setView, role }: { setView: (v: View) => void; role: 'feirante' | 'organizador' }) { return <aside className="dashboard-nav"><Logo /><div className="user-chip"><div className="avatar">GA</div><div><b>Gustavo Andrade</b><small>{role === 'feirante' ? 'Feirante' : 'Organizador'}</small></div></div><nav><button className="active"><Home size={17} /> Visão geral</button><button onClick={() => setView(role === 'feirante' ? 'catalogo' : 'minhas-feiras')}><Store size={17} /> {role === 'feirante' ? 'Meu catálogo' : 'Minhas feiras'}</button><button><Bell size={17} /> Convites <span className="nav-count">3</span></button><button><Settings size={17} /> Configurações</button></nav><button className="dashboard-exit" onClick={() => setView('home')}>Sair da conta</button></aside> }
function Dashboard({ setView, role = 'feirante' }: { setView: (v: View) => void; role?: 'feirante' | 'organizador' }) { const organizer = role === 'organizador'; return <main className="dashboard"><DashboardNav setView={setView} role={role} /><section className="dashboard-content"><div className="dashboard-top"><div><span className="kicker">BOM DIA, GUSTAVO</span><h1>{organizer ? 'Vamos movimentar a cidade.' : 'Seu catálogo está vivo.'}</h1></div><button className="icon-button"><Bell size={19} /></button></div><div className="stats"><div><span>{organizer ? 'Feiras ativas' : 'Produtos publicados'}</span><strong>{organizer ? '04' : '12'}</strong><small className="positive">+2 este mês</small></div><div><span>{organizer ? 'Feirantes parceiros' : 'Visualizações no mês'}</span><strong>{organizer ? '38' : '1.248'}</strong><small className="positive">+18,4%</small></div><div><span>{organizer ? 'Próxima feira' : 'Convites recebidos'}</span><strong>{organizer ? '21/09' : '03'}</strong><small>Jardim Iririú</small></div></div><div className="dashboard-columns"><div className="panel"><div className="panel-head"><div><span className="kicker">{organizer ? 'AGENDA' : 'ATIVIDADE RECENTE'}</span><h2>{organizer ? 'Suas próximas feiras' : 'Seus produtos'}</h2></div><button className="text-link" onClick={() => setView(organizer ? 'minhas-feiras' : 'catalogo')}>Ver tudo <ArrowRight size={15} /></button></div>{(organizer ? markets : products).slice(0, 3).map((item: any, index) => <div className="activity-row" key={item.name}><div className={`mini-art ${item.color}`}>{item.emoji}</div><div><b>{item.name}</b><span>{organizer ? item.date : item.vendor}</span></div><span className="row-status">{organizer ? `${item.vendors} participantes` : item.price}</span><Pencil size={15} /></div>)}</div><div className="panel invite-panel"><div className="panel-head"><div><span className="kicker">PENDÊNCIAS</span><h2>Convites recebidos</h2></div><span className="notification-dot">3</span></div><p>Você foi convidado para participar de novas feiras.</p><Button variant="soft"><Users size={16} /> Ver convites</Button></div></div><div className="quick-actions"><Button onClick={() => setView(organizer ? 'nova-feira' : 'catalogo')}><Plus size={17} /> {organizer ? 'Criar nova feira' : 'Adicionar produto'}</Button><Button variant="outline"><CircleUserRound size={17} /> Editar perfil</Button></div></section></main> }
function Manage({ setView, organizer = false }: { setView: (v: View) => void; organizer?: boolean }) { return <main className="dashboard"><DashboardNav setView={setView} role={organizer ? 'organizador' : 'feirante'} /><section className="dashboard-content"><button className="back-link" onClick={() => setView(organizer ? 'organizador' : 'feirante')}><ArrowLeft size={16} /> Voltar para visão geral</button><div className="dashboard-top manage-title"><div><span className="kicker">{organizer ? 'ORGANIZAÇÃO' : 'SEU NEGÓCIO'}</span><h1>{organizer ? 'Minhas feiras' : 'Meu catálogo'}</h1><p>{organizer ? 'Crie experiências que aproximam a cidade.' : 'Mostre o que você faz de melhor.'}</p></div><Button onClick={() => setView(organizer ? 'nova-feira' : 'catalogo')}><Plus size={17} /> {organizer ? 'Nova feira' : 'Novo produto'}</Button></div><div className="manage-grid">{(organizer ? markets : products).map((item: any) => <div className="manage-card" key={item.name}><div className={`mini-art large ${item.color}`}>{item.emoji}</div><div className="manage-card-body"><span className="tag">{organizer ? 'PUBLICADA' : item.category}</span><h3>{item.name}</h3><p>{organizer ? `${item.date} · ${item.place}` : item.price}</p><div><button className="text-link"><Pencil size={14} /> Editar</button><button className="text-link"><ArrowRight size={14} /> Ver detalhes</button></div></div></div>)}</div></section></main> }
function NewForm({ setView }: { setView: (v: View) => void }) { return <main className="dashboard"><DashboardNav setView={setView} role="organizador" /><section className="dashboard-content form-page"><button className="back-link" onClick={() => setView('organizador')}><ArrowLeft size={16} /> Voltar</button><div className="form-heading"><span className="kicker">NOVA EXPERIÊNCIA</span><h1>Crie uma feira.</h1><p>Conte para a cidade onde e quando vocês vão se encontrar.</p></div><form className="wide-form" onSubmit={e => { e.preventDefault(); setView('minhas-feiras') }}><div className="form-grid"><label>Nome da feira<input placeholder="Ex: Feira do Jardim" required /></label><label>Data<input type="date" required /></label><label className="full">Endereço<input placeholder="Ex: Praça do Jardim Iririú" required /></label><label>Horário de início<input type="time" required /></label><label>Horário de encerramento<input type="time" required /></label><label className="full">Uma breve descrição<textarea placeholder="O que as pessoas vão encontrar por aqui?" rows={4}></textarea></label></div><div className="form-actions"><Button variant="outline" onClick={() => setView('organizador')}>Cancelar</Button><Button type="submit">Publicar feira <ArrowRight size={16} /></Button></div></form></section></main> }
function Manual({ setView }: { setView: (v: View) => void }) { const examples = [{ label: 'Descoberta', title: 'Feiras próximas', text: 'A pessoa encontra eventos por localização, data e distância.', view: 'feiras' as View }, { label: 'Catálogo', title: 'Produtos perto de você', text: 'A busca mostra produtos, categorias, preços e produtores.', view: 'produtos' as View }, { label: 'Detalhe', title: 'Página da feira', text: 'O visitante vê endereço, horário, produtores e produtos disponíveis.', view: 'feira' as View }, { label: 'Gestão', title: 'Dashboard do feirante', text: 'O feirante acompanha produtos publicados, convites e visualizações.', view: 'feirante' as View }, { label: 'Organização', title: 'Minhas feiras', text: 'O organizador gerencia eventos e cria uma nova feira.', view: 'organizador' as View }, { label: 'Cadastro', title: 'Criar uma conta', text: 'A entrada orienta cada perfil para o próximo passo.', view: 'cadastro' as View }]; return <Shell setView={setView}><section className="manual-hero"><div><span className="kicker">GUIA RÁPIDO</span><h1>Manual de uso<br /><em>do Achei na Feira.</em></h1><p>Um mapa simples das telas e dos caminhos principais da plataforma.</p></div><div className="manual-index"><BookOpen size={24} /><span>06 telas<br /><b>para explorar</b></span></div></section><section className="manual-content"><div className="manual-intro"><span className="kicker">COMO USAR</span><h2>Escolha um caminho.</h2><p>Use os botões abaixo para abrir cada exemplo de página no protótipo. Os dados são demonstrativos e servem para apresentar a experiência visual.</p></div><div className="manual-grid">{examples.map((example, index) => <button className="manual-card" key={example.title} onClick={() => setView(example.view)}><span className="manual-number">0{index + 1}</span><span className="kicker">{example.label}</span><h3>{example.title}</h3><p>{example.text}</p><span className="text-link">Ver exemplo <ArrowRight size={15} /></span></button>)}</div></section><section className="manual-steps"><div><span className="kicker">FLUXOS PRINCIPAIS</span><h2>Da descoberta<br />à participação.</h2></div><ol><li><b>1. Descubra</b><span>Entre em Feiras ou Produtos pelo menu principal.</span></li><li><b>2. Explore</b><span>Use busca, localização e filtros para encontrar o que combina com você.</span></li><li><b>3. Participe</b><span>Abra os detalhes da feira e escolha visitar, salvar ou conhecer produtores.</span></li></ol></section></Shell> }
function RouterPage() {
  const navigate = useNavigate()
  const setView = (view: View) => navigate(view === 'home' ? '/' : `/${view}`)
  const props = { setView }

  return <Routes>
    <Route path="/" element={<HomePage {...props} />} />
    <Route path="/feiras" element={<Listing {...props} />} />
    <Route path="/produtos" element={<Listing {...props} productsOnly />} />
    <Route path="/feira" element={<FairDetail {...props} />} />
    <Route path="/login" element={<Auth {...props} />} />
    <Route path="/cadastro" element={<Auth {...props} signup />} />
    <Route path="/feirante" element={<Dashboard {...props} />} />
    <Route path="/catalogo" element={<Manage {...props} />} />
    <Route path="/organizador" element={<Dashboard {...props} role="organizador" />} />
    <Route path="/minhas-feiras" element={<Manage {...props} organizer />} />
    <Route path="/nova-feira" element={<NewForm {...props} />} />
    <Route path="/manual" element={<Manual {...props} />} />
    <Route path="*" element={<Navigate to="/" replace />} />
  </Routes>
}

export default function App() {
  return <BrowserRouter><RouterPage /></BrowserRouter>
}
